name: Update WAProto

on:
  push:
    branches:
    - auto-update-proto

jobs:
  update-proto:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install packages
      run: yarn --cwd proto-extract
    
    - name: Update WAProto.proto
      run: yarn --cwd proto-extract start

    - name: GenerateStatics
      run: yarn --cwd proto-extract pbjs -t static-module -w commonjs -o ../WAProto/index.js ../WAProto/WAProto.proto   
 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          add-paths: |
            WAProto/*
